name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment (dev/prd)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd

jobs:
  terraform-iam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Init Terraform
        run: terraform init -backend-config=backends/${{ inputs.env }}.config
      - name: Terraform Plan
        run: terraform plan -var-file=vars/${{ inputs.env }}.tfvars
      - name: Terraform Apply (on tag only)
        # if: startsWith(github.ref, 'refs/tags/')
        run: terraform apply -auto-approve -var-file=vars/${{ inputs.env }}.tfvars
